version: "3.4"

services:
  bot:
    image: bot
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile

    env_file:
      - .env

    links:
      - postgres:postgres

    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts:/scripts

volumes:
  postgres-data: {}
